name:                singing-trainer
version:             0.1.0.0
github:              "githubuser/singing-trainer"
license:             BSD3
author:              "Matthew Kuss"
maintainer:          "matthew.j.kuss@gmail.com"
copyright:           "2019 Matthew Kuss"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/matthewjkuss/singing-trainer#readme>

dependencies:
- base >= 4.7 && < 5
- GLUT == 2.7.0.14
- random == 1.1
- Euterpea == 2.0.6
- PortMidi == 0.1.6.1

library:
  source-dirs: src

executables:
  singing-trainer-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - singing-trainer

tests:
  singing-trainer-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - singing-trainer
